# Generated by Django 5.0 on 2024-01-01 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_account_is_superuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
